version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: host.docker.internal  # Utilisé pour que Docker accède à MySQL sur l'hôte
      DB_USER: root  # Utilisateur de MySQL
      DB_PASSWORD: ""  # Mot de passe de MySQL (mettez-en un si nécessaire)
      DB_NAME: inscription # Nom de la base de données
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7  # Utilisation de MySQL version 5.7
    environment:
      MYSQL_ROOT_PASSWORD: root  # Mot de passe du root de MySQL
      MYSQL_DATABASE: inscription  # Nom de la base de données
    ports:
      - "3306:3306"  # Expose le port MySQL à l'extérieur
